# Generated by Django 3.0.8 on 2020-07-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalconference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='prey',
            field=models.ManyToManyField(blank=True, to='animalconference.Animal'),
        ),
    ]
