# Generated by Django 3.0.8 on 2020-07-18 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalconference', '0002_auto_20200711_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('animalconference.animal',),
        ),
        migrations.AddField(
            model_name='animal',
            name='habitat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animalconference.Habitat'),
            preserve_default=False,
        ),
    ]
