# Generated by Django 2.2 on 2020-07-07 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('carnivorous', models.BooleanField()),
                ('predator_index', models.PositiveIntegerField()),
                ('prey', models.ManyToManyField(to='animalconference.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(related_name='seminars_attending', to='animalconference.Animal')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminars_hosting', to='animalconference.Animal')),
            ],
        ),
    ]
