# Generated by Django 2.2 on 2020-06-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavalidation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failingobjects',
            name='comment',
            field=models.TextField(max_length=250),
        ),
    ]
