# Generated by Django 3.0.8 on 2020-07-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavalidation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
