# Generated by Django 3.0.8 on 2020-07-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datavalidation', '0002_validator_execution_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validator',
            name='is_class_method',
        ),
    ]
