# Generated by Django 3.0.8 on 2020-07-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavalidation', '0003_remove_validator_is_class_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='description',
            field=models.TextField(),
        ),
    ]
