# Generated by Django 2.2 on 2020-06-27 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datavalidation', '0003_auto_20200626_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failingobjects',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failing_objects', to='datavalidation.Validator'),
        ),
    ]
